from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    emp_id = models.CharField(max_length=12)
    emp_name = models.CharField(max_length=200)
    emp_desi = models.CharField(max_length=200)
    emp_rm1 = models.CharField(max_length=200)
    emp_rm2 = models.CharField(max_length=200)
    emp_rm3 = models.CharField(max_length=200)
    emp_process = models.CharField(max_length=200)
    emp_doj=models.DateField()
    level = models.CharField(max_length=200)
    grade = models.CharField(max_length=200)

class PartA_Appraisee(models.Model):
    appraisee = models.OneToOneField(User, on_delete=models.CASCADE)
    emp_id = models.CharField(max_length=12)
    emp_name = models.CharField(max_length=200)
    emp_desi = models.CharField(max_length=200)
    emp_rm1 = models.CharField(max_length=200)
    emp_rm2 = models.CharField(max_length=200)
    emp_rm3 = models.CharField(max_length=200)
    emp_process = models.CharField(max_length=200)
    supervisor_name=models.CharField(max_length=150,null=True,blank=True)
    supervisor_desig=models.CharField(max_length=150,null=True,blank=True)
    reviewers_name=models.CharField(max_length=150,null=True,blank=True)
    reviewers_desig=models.CharField(max_length=150,null=True,blank=True)
    revenue_apcomment=models.TextField()
    revenue_rating = models.FloatField()
    ebitda_rating=models.FloatField()
    ebitda_apcomment=models.TextField()
    attrition_rating=models.FloatField()
    attrition_apcomment=models.TextField()
    absenteeism_rating=models.FloatField()
    absenteeism_apcomment=models.TextField()
    scheduleadherence_rating=models.FloatField()
    scheduleadherence_apcomment=models.TextField()
    mangr_revenue_apcomment = models.TextField(null=True)
    mangr_revenue_rating = models.FloatField(null=True)
    mangr_ebitda_rating = models.FloatField(null=True)
    mangr_ebitda_apcomment = models.TextField(null=True)
    mangr_attrition_rating = models.FloatField(null=True)
    mangr_attrition_apcomment = models.TextField(null=True)
    mangr_absenteeism_rating = models.FloatField(null=True)
    mangr_absenteeism_apcomment = models.TextField(null=True)
    mangr_scheduleadherence_rating = models.FloatField(null=True)
    mangr_scheduleadherence_apcomment = models.TextField(null=True)
    mangr_specialcomment = models.TextField(null=True)


class PartB_Appraisee(models.Model):
    appraisee = models.OneToOneField(User, on_delete=models.CASCADE)
    emp_id = models.CharField(max_length=12)
    emp_rm1 = models.CharField(max_length=200)
    emp_rm2 = models.CharField(max_length=200)
    emp_rm3 = models.CharField(max_length=200)

    one_rating = models.IntegerField()
    two_rating = models.IntegerField()
    three_rating = models.IntegerField()
    four_rating = models.IntegerField()
    five_rating = models.IntegerField()
    six_rating = models.IntegerField()
    seven_rating = models.IntegerField()
    eight_rating = models.IntegerField()
    nine_rating = models.IntegerField()
    ten_rating = models.IntegerField()
    eleven_rating = models.IntegerField()
    twelve_rating = models.IntegerField()
    thirteen_rating = models.IntegerField()
    fourteen_rating = models.IntegerField()
    fifteen_rating = models.IntegerField()
    sixteen_rating = models.IntegerField()
    seventeen_rating = models.IntegerField()
    eighteen_rating = models.IntegerField()

    one_rating_2 = models.IntegerField()
    two_rating_2 = models.IntegerField()
    three_rating_2 = models.IntegerField()
    four_rating_2 = models.IntegerField()
    five_rating_2 = models.IntegerField()
    six_rating_2 = models.IntegerField()
    seven_rating_2 = models.IntegerField()
    eight_rating_2 = models.IntegerField()
    nine_rating_2 = models.IntegerField()
    ten_rating_2 = models.IntegerField()
    eleven_rating_2 = models.IntegerField()

    one_rating_3 = models.IntegerField()
    two_rating_3 = models.IntegerField()
    three_rating_3 = models.IntegerField()
    four_rating_3 = models.IntegerField()
    five_rating_3 = models.IntegerField()
    six_rating_3 = models.IntegerField()
    seven_rating_3 = models.IntegerField()
    eight_rating_3 = models.IntegerField()

    one_rating_4 = models.IntegerField()
    two_rating_4 = models.IntegerField()
    three_rating_4 = models.IntegerField()
    four_rating_4 = models.IntegerField()
    five_rating_4 = models.IntegerField()
    six_rating_4 = models.IntegerField()
    seven_rating_4 = models.IntegerField()
    eight_rating_4 = models.IntegerField()
    nine_rating_4 = models.IntegerField()
    ten_rating_4 = models.IntegerField()
    eleven_rating_4 = models.IntegerField()
    twelve_rating_4 = models.IntegerField()
    thirteen_rating_4 = models.IntegerField()
    fourteen_rating_4 = models.IntegerField()
    fifteen_rating_4 = models.IntegerField()
    sixteen_rating_4 = models.IntegerField()
    seventeen_rating_4 = models.IntegerField()
    eighteen_rating_4 = models.IntegerField()
    nineteen_rating_4 = models.IntegerField()
    twenty_rating_4 = models.IntegerField()
    twentyone_rating_4 = models.IntegerField()
    twentytwo_rating_4 = models.IntegerField()
    twentythree_rating_4 = models.IntegerField()


    one_comment = models.TextField()
    two_comment = models.TextField()
    three_comment = models.TextField()
    four_comment = models.TextField()
    five_comment = models.TextField()
    six_comment = models.TextField()
    seven_comment = models.TextField()
    eight_comment = models.TextField()
    nine_comment = models.TextField()
    ten_comment = models.TextField()
    eleven_comment = models.TextField()
    twelve_comment= models.TextField()
    thirteen_comment = models.TextField()
    fourteen_comment = models.TextField()
    fifteen_comment = models.TextField()
    sixteen_comment = models.TextField()
    seventeen_comment = models.TextField()
    eighteen_comment = models.TextField()

    one_comment_2 = models.TextField()
    two_comment_2 = models.TextField()
    three_comment_2 = models.TextField()
    four_comment_2 = models.TextField()
    five_comment_2 = models.TextField()
    six_comment_2 = models.TextField()
    seven_comment_2 = models.TextField()
    eight_comment_2 = models.TextField()
    nine_comment_2 = models.TextField()
    ten_comment_2 = models.TextField()
    eleven_comment_2 = models.TextField()
    one_comment_3 = models.TextField()
    two_comment_3 = models.TextField()
    three_comment_3 = models.TextField()
    four_comment_3 = models.TextField()
    five_comment_3 = models.TextField()
    six_comment_3 = models.TextField()
    seven_comment_3 = models.TextField()
    eight_comment_3 = models.TextField()
    one_comment_4 = models.TextField()
    two_comment_4 = models.TextField()
    three_comment_4 = models.TextField()
    four_comment_4 = models.TextField()
    five_comment_4 = models.TextField()
    six_comment_4 = models.TextField()
    seven_comment_4 = models.TextField()
    eight_comment_4 = models.TextField()
    nine_comment_4 = models.TextField()
    ten_comment_4 = models.TextField()
    eleven_comment_4 = models.TextField()
    twelve_comment_4 = models.TextField()
    thirteen_comment_4 = models.TextField()
    fourteen_comment_4 = models.TextField()
    fifteen_comment_4 = models.TextField()
    sixteen_comment_4 = models.TextField()
    seventeen_comment_4 = models.TextField()
    eighteen_comment_4 = models.TextField()
    nineteen_comment_4 = models.TextField()
    twenty_comment_4 = models.TextField()
    twentyone_comment_4 = models.TextField()
    twentytwo_comment_4 = models.TextField()
    twentythree_comment_4 = models.TextField()

    mangr_one_rating=models.IntegerField(null=True,blank=True)
    mangr_two_rating=models.IntegerField(null=True,blank=True)
    mangr_three_rating=models.IntegerField(null=True,blank=True)
    mangr_four_rating=models.IntegerField(null=True,blank=True)
    mangr_five_rating=models.IntegerField(null=True,blank=True)
    mangr_six_rating=models.IntegerField(null=True,blank=True)
    mangr_seven_rating=models.IntegerField(null=True,blank=True)
    mangr_eight_rating=models.IntegerField(null=True,blank=True)
    mangr_nine_rating=models.IntegerField(null=True,blank=True)
    mangr_ten_rating=models.IntegerField(null=True,blank=True)
    mangr_eleven_rating=models.IntegerField(null=True,blank=True)
    mangr_twelve_rating=models.IntegerField(null=True,blank=True)
    mangr_thirteen_rating=models.IntegerField(null=True,blank=True)
    mangr_fourteen_rating=models.IntegerField(null=True,blank=True)
    mangr_fifteen_rating=models.IntegerField(null=True,blank=True)
    mangr_sixteen_rating=models.IntegerField(null=True,blank=True)
    mangr_seventeen_rating=models.IntegerField(null=True,blank=True)
    mangr_eighteen_rating=models.IntegerField(null=True,blank=True)
    mangr_one_rating_2=models.IntegerField(null=True,blank=True)
    mangr_two_rating_2=models.IntegerField(null=True,blank=True)
    mangr_three_rating_2=models.IntegerField(null=True,blank=True)
    mangr_four_rating_2=models.IntegerField(null=True,blank=True)
    mangr_five_rating_2=models.IntegerField(null=True,blank=True)
    mangr_six_rating_2=models.IntegerField(null=True,blank=True)
    mangr_seven_rating_2=models.IntegerField(null=True,blank=True)
    mangr_eight_rating_2=models.IntegerField(null=True,blank=True)
    mangr_nine_rating_2=models.IntegerField(null=True,blank=True)
    mangr_ten_rating_2=models.IntegerField(null=True,blank=True)
    mangr_eleven_rating_2=models.IntegerField(null=True,blank=True)
    mangr_one_rating_3=models.IntegerField(null=True,blank=True)
    mangr_two_rating_3=models.IntegerField(null=True,blank=True)
    mangr_three_rating_3=models.IntegerField(null=True,blank=True)
    mangr_four_rating_3=models.IntegerField(null=True,blank=True)
    mangr_five_rating_3=models.IntegerField(null=True,blank=True)
    mangr_six_rating_3=models.IntegerField(null=True,blank=True)
    mangr_seven_rating_3=models.IntegerField(null=True,blank=True)
    mangr_eight_rating_3=models.IntegerField(null=True,blank=True)
    mangr_one_rating_4=models.IntegerField(null=True,blank=True)
    mangr_two_rating_4=models.IntegerField(null=True,blank=True)
    mangr_three_rating_4=models.IntegerField(null=True,blank=True)
    mangr_four_rating_4=models.IntegerField(null=True,blank=True)
    mangr_five_rating_4=models.IntegerField(null=True,blank=True)
    mangr_six_rating_4=models.IntegerField(null=True,blank=True)
    mangr_seven_rating_4=models.IntegerField(null=True,blank=True)
    mangr_eight_rating_4=models.IntegerField(null=True,blank=True)
    mangr_nine_rating_4=models.IntegerField(null=True,blank=True)
    mangr_ten_rating_4=models.IntegerField(null=True,blank=True)
    mangr_eleven_rating_4=models.IntegerField(null=True,blank=True)
    mangr_twelve_rating_4=models.IntegerField(null=True,blank=True)
    mangr_thirteen_rating_4=models.IntegerField(null=True,blank=True)
    mangr_fourteen_rating_4=models.IntegerField(null=True,blank=True)
    mangr_fifteen_rating_4=models.IntegerField(null=True,blank=True)
    mangr_sixteen_rating_4=models.IntegerField(null=True,blank=True)
    mangr_seventeen_rating_4=models.IntegerField(null=True,blank=True)
    mangr_eighteen_rating_4=models.IntegerField(null=True,blank=True)
    mangr_nineteen_rating_4=models.IntegerField(null=True,blank=True)
    mangr_twenty_rating_4=models.IntegerField(null=True,blank=True)
    mangr_twentyone_rating_4=models.IntegerField(null=True,blank=True)
    mangr_twentytwo_rating_4=models.IntegerField(null=True,blank=True)
    mangr_twentythree_rating_4=models.IntegerField(null=True,blank=True)

    mangr_one_comment = models.TextField(null=True,blank=True)
    mangr_two_comment = models.TextField(null=True,blank=True)
    mangr_three_comment = models.TextField(null=True,blank=True)
    mangr_four_comment = models.TextField(null=True,blank=True)
    mangr_five_comment = models.TextField(null=True,blank=True)
    mangr_six_comment = models.TextField(null=True,blank=True)
    mangr_seven_comment = models.TextField(null=True,blank=True)
    mangr_eight_comment = models.TextField(null=True,blank=True)
    mangr_nine_comment = models.TextField(null=True,blank=True)
    mangr_ten_comment = models.TextField(null=True,blank=True)
    mangr_eleven_comment = models.TextField(null=True,blank=True)
    mangr_twelve_comment = models.TextField(null=True,blank=True)
    mangr_thirteen_comment = models.TextField(null=True,blank=True)
    mangr_fourteen_comment = models.TextField(null=True,blank=True)
    mangr_fifteen_comment = models.TextField(null=True,blank=True)
    mangr_sixteen_comment = models.TextField(null=True,blank=True)
    mangr_seventeen_comment = models.TextField(null=True,blank=True)
    mangr_eighteen_comment = models.TextField(null=True,blank=True)
    mangr_one_comment_2 = models.TextField(null=True,blank=True)
    mangr_two_comment_2 = models.TextField(null=True,blank=True)
    mangr_three_comment_2 = models.TextField(null=True,blank=True)
    mangr_four_comment_2 = models.TextField(null=True,blank=True)
    mangr_five_comment_2 = models.TextField(null=True,blank=True)
    mangr_six_comment_2 = models.TextField(null=True,blank=True)
    mangr_seven_comment_2 = models.TextField(null=True,blank=True)
    mangr_eight_comment_2 = models.TextField(null=True,blank=True)
    mangr_nine_comment_2 = models.TextField(null=True,blank=True)
    mangr_ten_comment_2 = models.TextField(null=True,blank=True)
    mangr_eleven_comment_2 = models.TextField(null=True,blank=True)
    mangr_one_comment_3 = models.TextField(null=True,blank=True)
    mangr_two_comment_3 = models.TextField(null=True,blank=True)
    mangr_three_comment_3 = models.TextField(null=True,blank=True)
    mangr_four_comment_3 = models.TextField(null=True,blank=True)
    mangr_five_comment_3 = models.TextField(null=True,blank=True)
    mangr_six_comment_3 = models.TextField(null=True,blank=True)
    mangr_seven_comment_3 = models.TextField(null=True,blank=True)
    mangr_eight_comment_3 = models.TextField(null=True,blank=True)
    mangr_one_comment_4 = models.TextField(null=True,blank=True)
    mangr_two_comment_4 = models.TextField(null=True,blank=True)
    mangr_three_comment_4 = models.TextField(null=True,blank=True)
    mangr_four_comment_4 = models.TextField(null=True,blank=True)
    mangr_five_comment_4 = models.TextField(null=True,blank=True)
    mangr_six_comment_4 = models.TextField(null=True,blank=True)
    mangr_seven_comment_4 = models.TextField(null=True,blank=True)
    mangr_eight_comment_4 = models.TextField(null=True,blank=True)
    mangr_nine_comment_4 = models.TextField(null=True,blank=True)
    mangr_ten_comment_4 = models.TextField(null=True,blank=True)
    mangr_eleven_comment_4 = models.TextField(null=True,blank=True)
    mangr_twelve_comment_4 = models.TextField(null=True,blank=True)
    mangr_thirteen_comment_4 = models.TextField(null=True,blank=True)
    mangr_fourteen_comment_4 = models.TextField(null=True,blank=True)
    mangr_fifteen_comment_4 = models.TextField(null=True,blank=True)
    mangr_sixteen_comment_4 = models.TextField(null=True,blank=True)
    mangr_seventeen_comment_4 = models.TextField(null=True,blank=True)
    mangr_eighteen_comment_4 = models.TextField(null=True,blank=True)
    mangr_nineteen_comment_4 = models.TextField(null=True,blank=True)
    mangr_twenty_comment_4 = models.TextField(null=True,blank=True)
    mangr_twentyone_comment_4 = models.TextField(null=True,blank=True)
    mangr_twentytwo_comment_4 = models.TextField(null=True,blank=True)
    mangr_twentythree_comment_4 = models.TextField(null=True,blank=True)





class PartC_Appraisee(models.Model):
    appraisee = models.OneToOneField(User, on_delete=models.CASCADE)
    emp_id = models.CharField(max_length=12)
    emp_rm1 = models.CharField(max_length=200)
    emp_rm2 = models.CharField(max_length=200)
    emp_rm3 = models.CharField(max_length=200)
    respect_rating = models.IntegerField()
    integrity_rating = models.IntegerField()
    diversity_rating = models.IntegerField()
    excellence_rating = models.IntegerField()
    teamwork_rating = models.IntegerField()
    respect_comment = models.TextField()
    integrity_comment = models.TextField()
    diversity_comment = models.TextField()
    excellence_comment = models.TextField()
    teamwork_comment = models.TextField()
    mangr_respect_rating = models.IntegerField(null=True,blank=True)
    mangr_integrity_rating = models.IntegerField(null=True,blank=True)
    mangr_diversity_rating = models.IntegerField(null=True,blank=True)
    mangr_excellence_rating = models.IntegerField(null=True,blank=True)
    mangr_teamwork_rating = models.IntegerField(null=True,blank=True)
    mangr_respect_comment = models.TextField(null=True,blank=True)
    mangr_integrity_comment = models.TextField(null=True,blank=True)
    mangr_diversity_comment = models.TextField(null=True,blank=True)
    mangr_excellence_comment = models.TextField(null=True,blank=True)
    mangr_teamwork_comment = models.TextField(null=True,blank=True)


class PartD_Appraisee(models.Model):
    appraisee = models.CharField(max_length=200)
    emp_id = models.CharField(max_length=12)
    emp_rm1 = models.CharField(max_length=200)
    emp_rm2 = models.CharField(max_length=200)
    emp_rm3 = models.CharField(max_length=200)
    strengths = models.TextField(blank=True, null=True)
    improvement_areas = models.TextField(blank=True, null=True)
    development_need_1 = models.TextField(blank=True, null=True)
    development_need_2 = models.TextField(blank=True, null=True)
    development_need_3 = models.TextField(blank=True, null=True)
    development_need_4 = models.TextField(blank=True, null=True)
    action_plan_1= models.TextField(blank=True, null=True)
    action_plan_2 = models.TextField(blank=True, null=True)
    action_plan_3= models.TextField(blank=True, null=True)
    action_plan_4= models.TextField(blank=True, null=True)
    responsibility_time_1 = models.TextField(blank=True, null=True)
    responsibility_time_2 = models.TextField(blank=True, null=True)
    responsibility_time_3 = models.TextField(blank=True, null=True)
    responsibility_time_4 = models.TextField(blank=True, null=True)
    desired_level_1 = models.TextField(blank=True, null=True)
    desired_level_2 = models.TextField(blank=True, null=True)
    desired_level_3 = models.TextField(blank=True, null=True)
    desired_level_4 = models.TextField(blank=True, null=True)
    train_identify_refitment = models.TextField(blank=True, null=True)
    coach_train_redeploy = models.TextField(blank=True, null=True)
    future_leaders = models.TextField(blank=True, null=True)
    need_development = models.TextField(blank=True, null=True)
    # solid_citizens_1 = models.TextField(blank=True, null=True)
    # solid_citizens_2 = models.TextField(blank=True, null=True)
    no_scope_improvement = models.TextField(blank=True, null=True)
    need_development_coach = models.TextField(blank=True, null=True)
    coach_on_value = models.TextField(blank=True, null=True)
    traing_type_1= models.TextField(blank=True, null=True)
    traing_type_2= models.TextField(blank=True, null=True)
    traing_type_3= models.TextField(blank=True, null=True)
    traing_type_4= models.TextField(blank=True, null=True)
    traing_type_5= models.TextField(blank=True, null=True)
    traing_time_1= models.TextField(blank=True, null=True)
    traing_time_2= models.TextField(blank=True, null=True)
    traing_time_3= models.TextField(blank=True, null=True)
    traing_time_4= models.TextField(blank=True, null=True)
    traing_time_5= models.TextField(blank=True, null=True)
    appraisee_roles=models.TextField(blank=True, null=True)
    appraisee_skills_required=models.TextField(blank=True, null=True)
    appraisee_time_frame=models.TextField(blank=True, null=True)
    agree=models.TextField(blank=True, null=True)
    if_disagree = models.TextField(blank=True, null=True)
    comments_feedback=models.TextField(blank=True, null=True)
