# Generated by Django 4.0.3 on 2022-04-21 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appraisalapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='agent_score',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='final_score',
        ),
    ]
