# Generated by Django 4.0.3 on 2022-04-21 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisalapp', '0002_remove_profile_agent_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='agent_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='final_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
