# Generated by Django 4.0.1 on 2022-01-11 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisalapp', '0006_alter_partb_appraisee_mangr_eight_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partb_appraisee',
            name='eighteen_comment',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='partb_appraisee',
            name='eighteen_rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='partb_appraisee',
            name='mangr_eighteen_comment',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='partb_appraisee',
            name='mangr_eighteen_rating',
            field=models.IntegerField(null=True),
        ),
    ]
