# Generated by Django 4.0.1 on 2022-01-11 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appraisalapp', '0008_remove_partb_appraisee_ninteen_comment_4_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partb_appraisee',
            old_name='mangr_ninteen_comment_4',
            new_name='mangr_nineteen_comment_4',
        ),
    ]
