# Generated by Django 4.0.1 on 2022-01-12 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appraisalapp', '0009_rename_mangr_ninteen_comment_4_partb_appraisee_mangr_nineteen_comment_4'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PartC_Appraisee',
        ),
        migrations.DeleteModel(
            name='PartD_Appraisee',
        ),
    ]
