# Generated by Django 4.0.1 on 2022-01-12 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisalapp', '0011_partc_appraisee_partd_appraisee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partc_appraisee',
            name='mangr_diversity_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partc_appraisee',
            name='mangr_diversity_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partc_appraisee',
            name='mangr_excellence_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partc_appraisee',
            name='mangr_excellence_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partc_appraisee',
            name='mangr_integrity_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partc_appraisee',
            name='mangr_integrity_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partc_appraisee',
            name='mangr_respect_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partc_appraisee',
            name='mangr_respect_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partc_appraisee',
            name='mangr_teamwork_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partc_appraisee',
            name='mangr_teamwork_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
