# Generated by Django 4.0.1 on 2022-01-12 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisalapp', '0012_alter_partc_appraisee_mangr_diversity_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_eight_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_eight_comment_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_eight_comment_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_eight_comment_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_eight_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_eight_rating_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_eight_rating_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_eight_rating_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_eighteen_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_eighteen_comment_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_eighteen_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_eighteen_rating_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_eleven_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_eleven_comment_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_eleven_comment_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_eleven_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_eleven_rating_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_eleven_rating_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_fifteen_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_fifteen_comment_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_fifteen_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_fifteen_rating_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_five_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_five_comment_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_five_comment_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_five_comment_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_five_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_five_rating_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_five_rating_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_five_rating_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_four_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_four_comment_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_four_comment_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_four_comment_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_four_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_four_rating_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_four_rating_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_four_rating_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_fourteen_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_fourteen_comment_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_fourteen_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_fourteen_rating_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_nine_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_nine_comment_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_nine_comment_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_nine_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_nine_rating_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_nine_rating_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_nineteen_comment_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_nineteen_rating_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_one_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_one_comment_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_one_comment_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_one_comment_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_one_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_one_rating_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_one_rating_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_one_rating_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_seven_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_seven_comment_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_seven_comment_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_seven_comment_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_seven_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_seven_rating_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_seven_rating_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_seven_rating_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_seventeen_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_seventeen_comment_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_seventeen_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_seventeen_rating_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_six_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_six_comment_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_six_comment_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_six_comment_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_six_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_six_rating_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_six_rating_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_six_rating_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_sixteen_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_sixteen_comment_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_sixteen_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_sixteen_rating_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_ten_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_ten_comment_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_ten_comment_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_ten_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_ten_rating_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_ten_rating_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_thirteen_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_thirteen_comment_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_thirteen_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_thirteen_rating_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_three_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_three_comment_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_three_comment_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_three_comment_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_three_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_three_rating_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_three_rating_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_three_rating_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_twelve_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_twelve_comment_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_twelve_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_twelve_rating_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_twenty_comment_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_twenty_rating_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_twentyone_comment_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_twentyone_rating_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_twentythree_comment_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_twentythree_rating_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_twentytwo_comment_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_twentytwo_rating_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_two_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_two_comment_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_two_comment_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_two_comment_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_two_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_two_rating_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_two_rating_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='mangr_two_rating_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='nineteen_comment_4',
            field=models.TextField(blank=True, null=True),
        ),
    ]
