# Generated by Django 4.0.1 on 2022-01-12 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisalapp', '0014_alter_parta_appraisee_appraisee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partb_appraisee',
            name='eighteen_comment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='eighteen_rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='partb_appraisee',
            name='nineteen_comment_4',
            field=models.TextField(),
        ),
    ]
