# Generated by Django 4.0.1 on 2022-01-12 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisalapp', '0015_alter_partb_appraisee_eighteen_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parta_appraisee',
            name='emp_desi',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parta_appraisee',
            name='emp_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parta_appraisee',
            name='emp_process',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
